version: '3.9'
name: tibia-info
services:
  postgresql-tibia-info:
    container_name: postgresql-tibia-info
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    networks:
      - network_tibia_info
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db-tibia-info
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-tibia-info:
    container_name: redis-tibia-info
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network_tibia_info
    volumes:
      - redis_data:/data

networks:
  network_tibia_info:
    driver: bridge

volumes:
  pgdata:
  redis_data:
