name: tibia-info
services:
#  app-tibia-info:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: tibia-info-back
#    ports:
#      - "3000:3000"
#    networks:
#      - network_tibia_info
#    depends_on:
#      - postgresql-tibia-info
#      - redis-tibia-info

  postgresql-tibia-info:
    container_name: postgresql-tibia-info
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    networks:
      - network_tibia_info
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db-tibia-info
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-tibia-info:
    image: redis:latest
    container_name: redis-tibia-info
    ports:
      - "6379:6379"
    networks:
      - network_tibia_info
    volumes:
      - redis_data:/data

networks:
  network_tibia_info:
    driver: bridge

volumes:
  pgdata:
  redis_data:
